### PR TITLE
Add Istanbul tests

### PR DESCRIPTION
**Pull request by s1na**
Update tests submodule to 52d5247 (Sep 22, 2019) which includes https://github.com/ethereum/tests/pull/639.

### CODE REVIEW

**Comment by holgerd77** [comment]
@s1na Great 👍, thought about this yesterday as well and prepared a release on the `Ethereum/tests` repo https://github.com/ethereum/tests/pull/640. This is close to be merged - now also containing the Blake2b `F` tests merged later this day. Let's please wait here with merging and then update directly to the `v7.0.0-beta.1` release tag.

Some grain of salt: the test repo contains various structural updates / changes on the directory structure, see the "Test Format Changes" section in the release notes (the biggest change being the introduction of this new legacy test suite, but also the `BlockchainTests` being moved to subfolders). This will likely make necessary some preparatory updates here on the library. We especially need to make sure that all tests are still run and no tests are just skipped due to folder changes.

Cheers
Holger

**Comment by holgerd77** [comment]
(if you want you can nevertheless directly start working/checking against the tests and opening a WIP PR on the VM side pointing to this PR here)

**Comment by s1na** [comment]
I updated the submodule to `v7.0.0-beta.1`.

Regarding the structural changes, what do you suggest we do? You mentioned that

> This will likely make necessary some preparatory updates here on the library. We especially need to make sure that all tests are still run and no tests are just skipped due to folder changes.

Do you have some specific preparatory updated in mind? Alternatively we could update how the other libraries import the tests.

**Comment by holgerd77** [comment]
@s1na Thanks for updating this, also wrote a short message on Gitter.

I would have a tendency to keep this completely transparent, so manage the changed folders internally here - so manage here some array of the legacy HFs and then internally fetch from the sub folder - and pass this on to the VM and keep the VM code unchanged.

That's just a "might be the easiest and eventually most tightly kept solution" suggestion, generally don't have a strong opinion on that.

**Comment by s1na** [comment]
> manage here some array of the legacy HFs and then internally fetch from the sub folder - and pass this on to the VM and keep the VM code unchanged.

Just had a look and it seems the VM doesn't query based on HF, but [queries directly](https://github.com/ethereumjs/ethereumjs-vm/blob/00d8fe3c7941fe571581fff1cd4e327980928127/tests/tester.js#L201) for source files. I also have a tendency to keep this repo as only a thin wrapper and have the logic of parsing test cases in the using code (e.g. VM).

That said, we might be able to modify [getTestsFromArgs](https://github.com/ethereumjs/ethereumjs-testing/blob/5d7c8b3ce1a1397b8674d0e351cd510e0c2b9797/index.js#L100) which accepts the fork as an arg, and choose files/subdirs based on that. Then modify VM to use this API.

**Comment by holgerd77** [comment]
@s1na Ok, just saw how you integrated, should we then leave this just "as is" and merge here? Given that there are so heavy changes in the submodule structure, I would give this at least a `v1.3.0` for release?

**Comment by s1na** [comment]
@holgerd77 sorry I somehow missed this message. I'd be okay with merging like this. I integrated these new tests in the VM and it wasn't much work. Yeah I agree with `v1.3.0`.

**Review by holgerd77 — APPROVED** [review]
Thanks Sina, ok, then I'll approve here and prepare the release notes. Also just [asked](https://github.com/ethereum/tests/pull/640#issuecomment-552811653) on the `tests` repo if it might be the time for another `beta` or eventually a final `Istanbul` release.

**Pull request merged**
