### PR TITLE
Clean up getTests function, remove async/await library

### LINKED ISSUE #37: Remove asyncawait library (browser compatibility)
The ``asyncawait`` library was introduced [here](https://github.com/ethereumjs/ethereumjs-testing/commit/f19f34b7d488ac0dc0960dec5aeaca4215a678c4), dated from October 2017 and with the goal to support Node 6.

This is causing browser compatibility problems in the VM and potentially other libraries, see https://github.com/ethereumjs/ethereumjs-vm/issues/465.

Since we have now dropped Node 6 https://github.com/ethereumjs/organization/pull/50 this PR can be reverted.

This should be followed by a new release (also updating the tests).

### PR DESCRIPTION
**Pull request by whymarrh**
Fixes #37

This PR cleans up `getTests`, also replacing the async-await library with native `async`/`await`.

### CODE REVIEW

**Comment by holgerd77** [comment]
CI is failing, can you also update this PR to run CI on Node 8, 10 and eventually 11?

**Comment by holgerd77** [comment]
We should really add https://github.com/ethereumjs/ethereumjs-config/issues/16 (Git hooks), I also stumble upon this regularly (linting errors). @whymarrh if you want you can open a small PR on this towards the blockchain or other library so that we get started, should be a pretty small one.

**Comment by whymarrh** [comment]
> CI is failing, can you also update this PR to run CI on Node 8, 10 and eventually 11?

On it

**Comment by whymarrh** [comment]
@holgerd77 should be good now, I cleaned up the Travis config as well

**Review by holgerd77 — CHANGES_REQUESTED** [review]
1. These code changes are rather heavy. Can you please add a test case for this method, since "getTests" is completely untested atm, so that we can make sure that API functionality is working as before?
2. Is Node 11 not working?
3. Can you please re-add the JSDoc comment for the method?

**Comment by whymarrh** [comment]
I added a test case for the default arguments, but I'm not quite sure how this is used in the wild—what other tests would be useful?

**Comment by rumkin** [comment]
While using async/await in source code it's better to set minimum node.js version to 8.0 in package.json:

```
{ "engines" : { "node" : ">=8.0" } }
```

And even better to define last tested version as an upper bound to avoid regression issues.

**Review by holgerd77 — APPROVED** [review]
Ok, have also done a short integration test on the VM, looks good! 😄

**Comment by holgerd77** [comment]
Hmm, might have been merged too early/quickly, the integration tests I did on the VM show a huge decrease in coverage - see https://github.com/ethereumjs/ethereumjs-vm/pull/477 - I think the blockchain tests are not run correctly (at all).

Can you have a look at that?

**Comment by whymarrh** [comment]
> Can you have a look at that?

I added a old commit hash to https://github.com/ethereumjs/ethereumjs-vm/pull/477 so we have something to compare against. I can take a look at what's happening—this is weird because we have a test for methods that the vm is using that used to pass as well.

**Comment by holgerd77** [comment]
You can have a look at the CI run, the state tests are just not running, respectively all skipped, this should likely be the cause for coverage decrease (see CircleCI coveralls run).

**Pull request merged**
