### PR TITLE
Update tests repo to 68728e13b

### PR DESCRIPTION
**Pull request by axic**
According to @pirapira the stable version of the tests repo is the commit hash used by cpp-ethereum 😉 

Do not merge this before https://github.com/ethereumjs/ethereumjs-vm/pull/272 is passing.

### CODE REVIEW

**Comment by holgerd77** [comment]
Maybe this should be documented in the ``ethereum/tests`` repo README.

**Comment by axic** [comment]
@holgerd77 I agree. Only figured out with asking @pirapira in person.

**Comment by pirapira** [comment]
@holgerd77 @axic I agree.  When I asked @winsvega he said `ethereum/tests:develop` should always be good.  I didn't know that.  The nice thing about the cpp-submodule is that it's tested in the cpp-ethereum CI process.

**Comment by holgerd77** [comment]
@pirapira maybe just mention both for different levels of reliability in the README.

**Comment by axic** [comment]
Relevant idea: https://gitter.im/testeth/Lobby?at=5a7ccb21e217167e2c5e585b

**Comment by holgerd77** [comment]
I've now updated this to the latest ``cpp-ethereum`` save-state (68728e13b). Will now retrigger the tests run on the VM working branch, this should fix at least some of the remaining failing tests.

**Review by holgerd77 — APPROVED** [review]
Corresponding VM PR test run is now passing.

**Pull request merged**
