### PR TITLE
Add support for loading a custom state test

### PR DESCRIPTION
**Pull request by jwasinger**
This corresponds to https://github.com/ethereumjs/ethereumjs-vm/pull/202 .

### CODE REVIEW

**Comment by holgerd77** [comment]
Can you also add a file to the ``examples/`` folder running this? This comes also pretty handy for own development and - since we have no tests here, maybe the next step - this is also good for executing at least once when changes are made to be sure that everything is working as expected.

Please also add a line to the README with the new method description.

**Comment by jwasinger** [comment]
The function is simple, self-explanatory and does not require a standalone example IMO

**Comment by holgerd77** [comment]
Added an example and a README not to this.

**Review by holgerd77 — APPROVED** [review]
LGTM, tested with example.

**Pull request merged**
